[versions]
# libraries
springBoot = "3.1.5"
springCloud = "2022.0.4"
cosid = "2.5.6"
testcontainers = "1.19.3"
guava = "32.1.3-jre"
commonsIo = "2.15.0"
hamcrest = "2.2"
mockk = "1.13.8"
detektFormatting = "1.23.3"
# plugins
detekt = "1.23.3"
dokka = "1.9.10"
kotlin = "1.9.20"
publishPlugin = "1.3.0"

[libraries]
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }
cosidBom = { module = "me.ahoo.cosid:cosid-bom", version.ref = "cosid" }
testcontainersBom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
commonsIo = { module = "commons-io:commons-io", version.ref = "commonsIo" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektFormatting" }
[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinkapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
publishPlugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publishPlugin" }

