[versions]
# libraries
springBoot = "3.1.2"
springCloud = "2022.0.4"
cosid = "2.5.0"
testcontainers = "1.19.0"
guava = "32.1.2-jre"
commonsIo = "2.13.0"
hamcrest = "2.2"
mockk = "1.13.7"
detektFormatting = "1.23.1"
# plugins
detekt = "1.23.1"
dokka = "1.8.20"
kotlin = "1.9.10"
publishPlugin = "1.3.0"

[libraries]
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }
cosidBom = { module = "me.ahoo.cosid:cosid-bom", version.ref = "cosid" }
testcontainersBom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
commonsIo = { module = "commons-io:commons-io", version.ref = "commonsIo" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektFormatting" }
[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinkapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
publishPlugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publishPlugin" }

